### ISSUE TITLE
Is it possible to make an inserter mod by itself? 

### ISSUE THREAD

**Issue by lh569218** [Valoneu/DysonSphereMods#11]
Overclocking takes effect on all buildings at the same time, and cannot be customized to upgrade a certain building. It would be nice to add this function if possible, the overclocking MOD is very useful, thank you for sharing, by the way, can you make a separate inserter MOD? （The above content is from google translate ）
超频对所有建筑物同时生效，不能自定义对某一个建筑进行升级。如果可以的话加上这个功能就好了，超频MOD很好用，感谢你的分享，顺便请问可以单独做一个插入器MOD么？

**Comment by Valoneu** [comment]
You can overclock only some buildings if you set them to 1x in config file. And why you want separate inserter MOD?

**Comment by lh569218** [comment]
I didn't make it clear what I meant. Check out this mod for details
"https://dsp.thunderstore.io/package/crecheng/AddBuild/1.2.0/"
(building stacking mod - using the same building can make your factory faster)
This mod feature upgrades the speed of a building individually, not the speed of that type of building. This allows for a more convenient layout. I used your factory overclock and building overlay mod at the same time and found that the factory overclock will force the building overlay effect to be overridden, causing confusion in the production line. But I would love to get a sorter. If there was a separate interposer mod, I could use building stacks at the same time. Of course, if it is more troublesome, it is not necessary, thank you very much for your reply.

**Comment by Valoneu** [comment]
I will put it in my todo list to do just inserter mod but i dont know when cause i dont have that much time maybe next week or so

**Comment by lh569218** [comment]
Thank you very much for your dedication!

**Comment by Valoneu** [comment]
so after the update i wanted to ask if you still need it
