### ISSUE TITLE
After the thermal power plant is overclocked, the power generation time is halved, and the power generation does not double 

### ISSUE THREAD

**Issue by lh569218** [Valoneu/DysonSphereMods#12]
When the power consumption of the smelter is doubled, the power generation time of the thermal power plant is halved (the time that the resource can support is halved), but the power generation does not double. I don’t know if it is because other mods cover the power generation doubling effect. Is this a problem with the increase in power when the factory overclocking MOD is not set to double the power?

**Comment by Valoneu** [comment]
well is that bcs of its requesting more power so the rescourse get used faster?

**Comment by Valoneu** [comment]
https://dsp.thunderstore.io/package/Taki7o7/EnergyManager_Generators/
if you want more power from generators ill add it after the 20th update

**Comment by lh569218** [comment]
Thanks for your reply, this is a solution to the problem
