### ISSUE TITLE
[TechHashReduce] Feature Request: Option to skip research that uses components instead of Matrix

### ISSUE THREAD

**Issue by w-gates** [Valoneu/DysonSphereMods#13]
I decided to challenge myself and set the TechHashReduce to 100. This has been fun so far (a lot more time to plan - which is needed since you spend so long with low upgrades - and to use intermediary tech that I used to skip over), and I would like to use it again in a future restart. 

The only thing that I am concerned about is how long the research that uses components instead of a Matrix took to complete at 100. I was fine with it this time because I was on vacation when I started and had lots of time, but next time I would probably avoid setting it so high if I have to wait through that again.

A neat feature would be a configuration option that prevented the mod value being used (or set a different value) for non-matrix tech/upgrades that can not be automated.

**Comment by Valoneu** [comment]
well cool idea but idk how to do it

**Comment by Valoneu** [comment]
ill get it in my todo list that you can see in readme in DSPmods
