### ISSUE TITLE
Game update causes mod to fail

### ISSUE THREAD

**Issue by lh569218** [Valoneu/DysonSphereMods#14]
It may be because the game has been updated, and now the mod has no acceleration effect. I look forward to the author to update the mod

**Comment by Valoneu** [comment]
can you give more info if its not working at all or only power works or only speed works, would help me :)

**Comment by lh569218** [comment]
Just tried again, Because of I turned off the mod feature，“Determine whether we are currently multiplying values：false” Caused the MOD to not work，I am sorry to bother you-_-!

**Comment by Valoneu** [comment]
its toggle able in the game too you can bind it in settings
