### ISSUE TITLE
[Bug] Seems to no longer work

### ISSUE THREAD

**Issue by Flam1ngDem0n** [Valoneu/DysonSphereMods#18]
Using the mod and at some point the game was updated and this mod no longer is working for me. I am using the toggle hotkey (even rebound it myself) and nothing happens. The power consumption doesn't increase and the output doesn't increase. Nothing changes. I am trying to toggle the feature on a Refinery Oil Extractor (from another mod). However I've tried toggling on base game content and it still does nothing.

**Comment by Valoneu** [comment]
Hi, have you tried using this https://dsp.thunderstore.io/package/waRNing525/FactoryMutiplier/ , it seems to do the same thing as me, i havent keep up with DS for like a year and i dont think i will be able to fix this mod for now.

**Comment by Valoneu** [comment]
This seems also same https://dsp.thunderstore.io/package/AlphaDSPMod/WorkingSpeedUp/

**Comment by Flam1ngDem0n** [comment]
Understood. Thank you for the alternatives! :)

**Comment by Flam1ngDem0n** [comment]
Tried both alts, neither work. Just letting you know. :)

**Comment by Valoneu** [comment]
ok, thanks. Ill try to look at it if some of them update their mod because this mod was mainly written by Semar and he wasnt online for like a year. I dont think im advanced enought to fix it but i could try too.
