### ISSUE TITLE
Power consumption is just doubled.

### ISSUE THREAD

**Issue by VTrista** [Valoneu/DysonSphereMods#9]
Just noticed a minor gripe with this mod.

When I installed it, all my machines drew double power, but didn't increase in production speed.

I didn't even change the config, just felt it as it appeared.

I assumed power draw to be "Multiplier^2", not "2xMultiplier" or something like that.

**Comment by Valoneu** [comment]
the power draw is multiplier * multiplier * powerdraw so on 1x it should be the same

**Comment by Valoneu** [comment]
ah yes sry fixed now it did not save

**Comment by Valoneu** [comment]
will update in like 2 min
